const express = require('express')
const server = require('express').Router()

const salesRouter = require('./SalesRouter')
const articlesRouter = require('./ArticleRouter')
const usersRouter = require('./UsersRouter')
const brandRouter = require('./BrandRouter')
const providerRouter = require('./ProviderRouter')
const reasonChangeRouter = require('./ReasonChangeRouter')
const taxRouter = require('./TaxConditionsRouter')
const paymentRouter = require('./PaymentRouter')
const rolesRouter = require('./RolesRouter')
const companyRouter = require('./CompanyRouter')

server.use('/sales', salesRouter)
server.use('/articles', articlesRouter)
server.use('/users', usersRouter)
server.use('/brand', brandRouter)
server.use('/provider', providerRouter)
server.use('/reasonchange', reasonChangeRouter)
server.use('/tax', taxRouter)
server.use('/payment', paymentRouter)
server.use('/roles', rolesRouter)
server.use('/company', companyRouter)